In [1]:
import pandas as pd

df=pd.read_excel("../data/ParsOffensive.xlsx")
df.head()

                                             comment      label
0  الان این فیلتر چه بادیگاردی هم براش گذاشتن یک ...  Offensive
1                                  سلام علیک سید جان    Neutral
2                                             سگ پدر  Offensive
3               خار چشم دشمنان ایران اسلامی سید عزیز    Neutral
4                             سلام علیک بر  سید عزیز    Neutral

In [2]:
import hazm

normalizer=hazm.Normalizer()
word_tokenizer=hazm.WordTokenizer()
lemmatizer=hazm.Lemmatizer()

def clean_stopword(stopword):
	return stopword.replace("آ", "ا")

stopwords=hazm.utils.stopwords_list()
stopwords=list(map(clean_stopword, stopwords))


for word in ["عالی", "خوب", "خوبی", "بی"]: stopwords.remove(word)

In [3]:
import string
import emoji
import numpy as np

def remove_chars(text, chars):
	for char in chars: text=text.replace(char, " ")
	return text

def preprocess(text):
	if not isinstance(text, str): return np.nan

	text=text.lower()
	text=remove_chars(text, string.punctuation+"؟،")

	text=emoji.replace_emoji(text, replace=" ")

	normalized_txt=normalizer.normalize(text).replace("آ", "ا")
	normalized_txt=remove_chars(normalized_txt, "۰۱۲۳۴۵۶۷۸۹\u200c")
	
	tokens=word_tokenizer.tokenize(normalized_txt)

	tokens=list(map(
		lambda token: lemmatizer.lemmatize(token).split("#")[0],
		tokens
	))

	tokens=list(filter(
		lambda token: token not in stopwords,
		tokens
	))

	if len(tokens)==0: return np.nan

	return " ".join(tokens)


df.comment=df.comment.apply(preprocess)
df.head()

                                       comment      label
0  الان فیلتر بادیگاردی براش گذاشت وقت لال نشه  Offensive
1                            سلام علیک سید جان    Neutral
2                                       سگ پدر  Offensive
3           خار چشم دشمن ایران اسلامی سید عزیز    Neutral
4                           سلام علیک سید عزیز    Neutral

In [4]:
print(df.isnull().sum())
df.dropna(inplace=True)
print(df.isnull().sum())
df.label.value_counts(normalize=True)

comment    170
label        0
dtype: int64
comment    0
label      0
dtype: int64

label
Neutral      0.628343
Offensive    0.371657
Name: proportion, dtype: float64

In [5]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer=TfidfVectorizer(
	ngram_range=(1, 2)
)

X=vectorizer.fit_transform(df.comment)

vectorizer.get_feature_names_out()

array(['npt', 'npt تولید', 'إسرائیلی', ..., 'یکیو عوض', 'یکیو یارست',
       'ییاد'], shape=(49810,), dtype=object)

In [6]:
import warnings
warnings.filterwarnings("ignore")

LABELS_DICT={"Neutral": 0, "Offensive": 1}
y=df.label.replace(LABELS_DICT, inplace=True).astype(int)
y

0       1
1       0
2       1
3       0
4       0
       ..
8428    0
8429    1
8430    1
8431    0
8432    0
Name: label, Length: 8263, dtype: int64

In [7]:
from sklearn.svm import LinearSVC

model=LinearSVC(class_weight="balanced")
model.fit(X, y)

LinearSVC(class_weight='balanced')

# Test

In [8]:
texts=[
    "خیلی مزخرف بود",
    "خیلی بی‌شعوری",
    "خیلی عالی بود",
    "واقعا جالب بود"
]

texts=list(map(preprocess, texts))

vecs=vectorizer.transform(texts)
predicts=model.predict(vecs)
print(predicts)
model._predict_proba_lr(vecs)

[1 1 0 0]

array([[0.24135965, 0.75864035],
       [0.27878422, 0.72121578],
       [0.71644883, 0.28355117],
       [0.74247531, 0.25752469]])